### ISSUE TITLE
Incorrect title when deleting a note

### ISSUE THREAD

**Issue by hihaiu** [mudita/MuditaOS#2134]
# 🐛 Bug report

## 📝 Description

When user is deleting a note the confirm dialog title is set incorrectly

## 👍 Expected behavior

Title is empty / Title shows some part of the note from the beginning

## 👎 Current behavior

Title is "Alarm Clock"

## 🔬 Minimal reproduction

1. Go to Menu -> Tools -> Notes
2. Select Options on one of the notes
3. Select Delete

## 🔍 Provide logs

Please paste relevant logs below or attach them to this issue.

<pre><code>
180481 ms DEBUG OptionWindow.cpp:onBeforeShow:120: Options load!
194681 ms DEBUG Application.cpp:pushWindow:867: App: ApplicationNotes window ConfirmDialog request
194681 ms ERROR RichTextParser.cpp:parse:527: no: text
194681 ms DEBUG Application.cpp:handleSwitchWindow:511: Current window: ConfirmDialog vs ConfirmDialog
194681 ms DEBUG Application.cpp:handleAppRefresh:575: Ignore request for window Options we are on window ConfirmDialog
</code></pre>

## 🌍 Your operating system and MuditaOS version
Ubuntu 20.04.2 LTS
commit: 35a280a0b tag: release-0.66.1-7-g35a280a0b
## 🤔 Anything else relevant?

**Comment by mjan-dev** [comment]
This issue doesn't occur in newest firmware. Closing.
