### ISSUE TITLE
Adding a new alarm

### ISSUE THREAD

**Issue by hihaiu** [mudita/MuditaOS#2135]
# 🐛 Bug report

## 📝 Description

When user adds a new alarm the added alarm will be +3 hours in alarms list.

## 👍 Expected behavior

New alarm is set to the exact time set by the user.

## 👎 Current behavior

New alarm is set +3 hours from the time that is set by the user

## 🔬 Minimal reproduction

1. Go to Menu -> Alarm
2. Add alarm ( + )
3. Set time and save
4. The new alarm is +3 hours from the user set value

## 🔍 Provide logs

Please paste relevant logs below or attach them to this issue.

<pre><code>
606738 ms DEBUG ApplicationAlarmClock.cpp:DataReceivedHandler:40: Received notification
606740 ms DEBUG AlarmsModel.cpp:getItem:43: Empty record in AlarmsModel::GetItem
</code></pre>

## 🌍 Your operating system and MuditaOS version
Ubuntu 20.04.2 LTS
commit: 35a280a tag: release-0.66.1-7-g35a280a0b
## 🤔 Anything else relevant?
Tested on timezone GMT+2 ( 8:45 PM )
MuditaOS time ( 9:45 PM )

The default time in set new alarm "form" is -3h from the MuditaOS time.

**Comment by pholat** [comment]
@hihaiu could you please retest with the current master? from the time the issue was raised this particular code was rewritten

**Comment by pholat** [comment]
please reopen if issue still exists.
