### ISSUE TITLE
code quality: designated initializers are not standard C++17

### ISSUE THREAD

**Issue by GravisZro** [mudita/MuditaOS#2383]
# ⚠️ Code Quality Issue

## 📝 Description

In many locations (in just about every `module-*` project) _designated initializers_  are used when initializing structures.  While this does function, it is not valid C++17 code.

> Example
`struct {`
`  int x;`
`  int y;`
` } a = { .y = 9 };`

## 📝 Describe the solution you'd like

Ideally, on should simply abide C++17 aggregate initialization or utilize `constexpr` constructors to initialize the data without additional overhead.

## 📝 Describe alternatives you've considered

You could change the project to C++20 because _designated initializers_  were [added in C++20](https://en.cppreference.com/w/cpp/20).  Then again, if you aren't sticklers then you can just ignore the use non-standard code.

**Comment by pholat** [comment]
Most parts of the code are GCC c++17 plus GCC extensions confirmation. That's not stated formally anywhere though.

We didn't decide to change to c++20, as we wait for better standard adoption and it was decided it's not worth doing so yet. Same with designated initializers - we can remove them, but there was no valid reason to do so - ad adding proper automatic checks would cost us some time, while giving us nothing in return.
