### ISSUE TITLE
Product option missing for configuration scripts

### ISSUE THREAD

**Issue by mdehollander** [mudita/MuditaOS#2814]
# 🐛 Bug report

First try building MuditaOS

## 📝 Description

I am giving a build of MuditaOS a first try and I get this error, both for the docker as local approach if I follow the instructions from the docs:
```
$ ./configure.sh linux Debug
Wrong product: "linux"
Wrong target: "Debug"
stop
```

## 👍 Expected behavior
It should build the image/executable

## 👎 Current behavior

Error saying wrong product and target

## 🔬 Minimal reproduction

```
$ ./configure.sh linux Debug
Wrong product: "linux"
Wrong target: "Debug"
stop
```

or 

```
$ ./in_docker.sh config linux Debug
```

## 🌍 Your operating system and MuditaOS version

Ubuntu 20.04 LTS

## 🤔 Anything else relevant?

Looking at the configure.sh help I see there needs to be a product option added to the command:

```
$ ./configure.sh --help
Use this script for faster configuring build types
ussage:
	./configure.sh [-dh] <product> <target> <build_type> [other cmake options]
options:
			d		- turn on development features
			h		- print this help
available products are:
			pure
			bell
available targets are:
			linux
			rt1051
available build types:
			Debug		- standard debug build
			Release		- release build (not for debugging)
			RelWithDebInfo	- release with debug info in separate file
```

Running it with pure as product option make it continue...

```
$ ./configure.sh pure linux Debug 
build dir:
	build-purephone-linux-Debug
cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=/home/mattiash/src/MuditaOS/Target_Linux.cmake -DPRODUCT=PurePhone 
```

**Comment by pholat** [comment]
Hi, unfortunately, we mostly use our local configurations and have a separate docker for CI builds, therefore it might have been a bit neglected. 

Saying that - what's missing is documentation mostly. To just compile the project you can run:
```
./in_docker.sh login
./configure.sh pure rt1051 relWithDebInfo  "-G Ninja"
ninja PurePhone.elf
```

Here are 3 important differences:
- as you can see it logs into the image
- configure uses Ninja.
- it builds only elf file

It should succeed, though we do not have an open-source binary assets configuration yet, therefore you won't be able to check it or use it much. As you see you've figured it out pretty much yoursleve.

If you happen to check it, feel free to update the docs it would be greatly appreciated! :bow:

**Comment by SP2FET** [comment]
The docs are already updated, so let me close the issue ;)
