### ISSUE TITLE
Minimum requirements

### ISSUE THREAD

**Issue by niutech** [mudita/MuditaOS#3337]
Please provide minimum requirements to run MuditaOS on a physical board with FreeRTOS. Will ESP32 with 8MB PSRAM be enough to boot it?

**Comment by wojtekrzepecki** [comment]
Most of the constraints are about memory usage. I.MX RT1051 microcontroller have 512KB of on-chip RAM which is utilized  for threads stacks, FreeRTOS heap etc.. Mudita Pure is equipped with 64MB of SDRAM. Here you can find memory utilization of the recent build:
![obraz](https://user-images.githubusercontent.com/74544942/144383635-a6be3e63-e0dc-4c0c-8c86-5ac86214d79e.png)
Mudita Harmony (in code: Bell) has 16MB of SDRAM and it's totally sufficient but the binary is much smaller (3,5MB).

You have to be aware that design was not optimized for low memory footprint, e.g. all images are loaded into heap at the system initialization. With some tricks 8MB of RAM may be enough to fit Harmony build. Running Pure Phone may be more problematic.

**Comment by wojtekrzepecki** [comment]
Most of the constraints are about memory usage. I.MX RT1051 microcontroller have 512KB of on-chip RAM which is utilized  for threads stacks, FreeRTOS heap etc.. Mudita Pure is equipped with 64MB of SDRAM. Here you can find memory utilization of the recent build:
![obraz](https://user-images.githubusercontent.com/74544942/144383635-a6be3e63-e0dc-4c0c-8c86-5ac86214d79e.png)
Mudita Harmony (in code: Bell) has 16MB of SDRAM and it's totally sufficient but the binary is much smaller (3,5MB).

You have to be aware that design was not optimized for low memory footprint, e.g. all images are loaded into heap at the system initialization. With some tricks 8MB of RAM may be enough to fit Harmony build. Running Pure Phone may be more problematic.

**Comment by niutech** [comment]
Thank you. How about processing power? Dual-core 240 MHz CPU should be enough to boot it, or do I need much more?

**Comment by wojtekrzepecki** [comment]
We are running Pure with top 528MHz CPU frequency, which is decreased most of the time according to cpu load dynamically. 240MHz should be enough.

**Comment by wojtekrzepecki** [comment]
@niutech Is this information sufficient for you? If yes, please close the issue :slightly_smiling_face:

**Comment by niutech** [comment]
Yes, thank you.
