### ISSUE TITLE
Truncated messages

### ISSUE THREAD

**Issue by snan** [mudita/MuditaOS#3403]
I received a long text message and it got truncated and I can't read the end of it. (I just called them up.)

**Comment by pholat** [comment]
@snan if you select this message, cant you scroll it up/down with `up` and `down` keys? :)

**Comment by snan** [comment]
I have already deleted it, but I've asked my friend to send a new long text so I can try what you ask. How do I select messages on the phone?

**Comment by snan** [comment]
Oooh! OK, that worked! So the issue is only visual / discoverability / UI (as opposed to UX).

Great!
