### ISSUE TITLE
Possible memory leaks between received messages

### ISSUE THREAD

**Issue by czalaviek** [mudita/MuditaOS#3424]
I observed today weird behaviour of messaging app. 1'st I've received message from my banking service (lack of number, only name like "PKO BP"). Message was cutted-off, only about 10 letters left. After a while, I've received next message, from my friend. To my surprise message was concatenated from rest of banking msg and original friend's text.

**Comment by mjan-dev** [comment]
Hi czalaviek!
Sorry to hear about the issue. Good thing is we are already working on it and we had it in backlog :) 
Here is some tracking number to see when it will appear on PR section. [EGD-6991](https://appnroll.atlassian.net/browse/EGD-6991)

**Comment by SP2FET** [comment]
Hi, 
Let me inform you that this issue has been fixed and will be included in the next release.

**Comment by czalaviek** [comment]
Great news!!!
