### ISSUE TITLE
Tethering not working

### ISSUE THREAD

**Issue by zalun** [mudita/MuditaOS#3558]
# 🐛 Bug report

## 📝 Attempt to connect via USB tethering is showing an error

- Connected to my MBP with a cable that allows data connection
- Pure is showing a message if I'd like to tether [YES]
- Mudita Pure appears as a Network connection in Network Preferences modal window
- I enter the connection settings for the OrangePL (*99#/internet/internet) (Advanced -> Model: GPRS, APN: Internet, CID: 1), Then I Apply them
- I hit the [Connect] button

## 👍 Expected behavior

A green light and Connected message next to the Mudita Pure name

## 👎 Current behavior

Immediately an error window pops up with a message: The communication device selected for your connection does not exist. Verify your settings and try reconnecting.

## 🔬 Minimal reproduction

The above steps are the right reproduction steps

## 🔍 Provide logs

I've got no idea how to get the logs

## 🌍 Your operating system and MuditaOS version

MacOS Monterey 12.1
Mudita 1.01 Mudita OS 1.1.6

## 🤔 Anything else relevant?

I've added the configuration for Network in the phone (it doesn't work either way)

I think I also failed to connect to the GPRS network using the OrangePL there is no indicator of it on the phone.

**Comment by SP2FET** [comment]
Hi,
Sorry to hear that you have trouble with the tethering. Have you tried installing the HoRNDIS driver for Mac? I think it should solve your problems :)
https://joshuawise.com/horndis

If it wasn't communicated to the users please let me know, I'll update the docs then.

**Comment by SP2FET** [comment]
According to the GPRS connection - there's no indicator in the OS, as the phone itself doesn't use cellular data. During tethering the modem is reconfigured and disconnected from the OS - there's a passthrough between the modem and the comupter.

**Comment by SP2FET** [comment]
@zalun did it fixed your issue?

**Comment by SP2FET** [comment]
In case the driver won't install properly, please take a look at this comment and follow it step-by-step:
https://github.com/jwise/HoRNDIS/issues/132#issuecomment-745607263

If it won't help with your tethering issue, please reopen the issue.

**Comment by ruario** [comment]
That does not help for me. After running the spctl -a -vv -t install command against the pkg it ends with:

```
HoRNDIS-9.2.pkg: rejected
source=no usable signature
```

Also do not like that you have to hack around this. Are you working on a proper solution for macOS users?
