### ISSUE TITLE
Unable to build unit tests without assets

### ISSUE THREAD

**Issue by GravisZro** [mudita/MuditaOS#3598]
# ⚠️ Build issue

## 📝 Description

I'm trying to run a unit test so that I can resolve the problem in PR #3322 but `make check` eventually invokes `download_assets.py` which fails and bombs the entire build process.

## 📝 Describe the solution you'd like

I would like to be able to make unit tests without requiring that assets be downloaded.

## 📝 Describe alternatives you've considered

I've tried actually getting the assets but it seems I need to be permitted access as described in #3597.  This is a real roadblock for anyone that wants to make a contribution.

**Comment by paweljonskim** [comment]
I posted on forum regarding the topic:
https://forum.mudita.com/t/muditaos-community-build/3911
You'll find details there :)
