### ISSUE TITLE
Receiving text messages

### ISSUE THREAD

**Issue by snan** [mudita/MuditaOS#3644]
N.B: this is still on the old version, 1.1.5.

I just received a message from my dentist who had promised to text the latest appointment. But, opening the message, I instead see a duplicate of a message from a parcel company making a delivery the other day. (That message is also what happened to be displayed as I last locked the phone yesterday, which might be significant, but it was also the last message I received, period.)

This problem persists as I leave and return to the messages app. As I restart the phone, it's worse. Messages are jumbled up, so  in my thread with the Dentist contact, the message starts with "You have a delivery etc etc" (parcel I picked up yesterday) but then the message cuts off (it doesn't even get to the parcel code I would've needed to pick it up) and switches over to the dentist message).

**Comment by niepiekm** [comment]
Hi, this issue is already addressed by PR #3512 and will be included in next OS release.
