### ISSUE TITLE
Sometimes long delay when switching to Connected mode

### ISSUE THREAD

**Issue by rawzen** [mudita/MuditaOS#3659]
When in Offline or Do not disturb mode, and switching to Connected it can sometimes take up to a minute to get visual feedback on screen that the mode has changed and network connection is resumed. Other times it only takes a few seconds.
Switching from Offline to Do not disturb happens immediately.

**Comment by SP2FET** [comment]
Hi, which firmware version are you using? The latest one (1.1.6)?

**Comment by rawzen** [comment]
Yes. It is version 1.1.6.

mån 21 mars 2022 kl. 08:36 skrev Bartosz Cichocki ***@***.***

**Comment by SP2FET** [comment]
Could you please confirm that after switching the slider to the next position you get a delay between switching the slider and info popup on the screen, or do you mean the delay between switching the connected mode and fully-operational modem?

**Comment by rawzen** [comment]
The long delay is between switching the slider to connected mode and the
info popup, and the network connection seems to be down until the info
popup appears on the screen.

mån 21 mars 2022 kl. 12:07 skrev Bartosz Cichocki ***@***.***

**Comment by SP2FET** [comment]
alright, thank you for the info, we'll investigate the issue and keep you informed if we found anytihng

**Comment by Lefucjusz** [comment]
@rawzen The issue has been fixed and will be present in one of the future releases.
