### ISSUE TITLE
Notification for unread messages are not cleared when messages are recieved while in messages app

### ISSUE THREAD

**Issue by rawzen** [mudita/MuditaOS#3660]
1. In the messages app sending and receiving messages.
2. All received messages are read.
3. When returning to menu or home screen there is still a notification for unread messages.

**Comment by SP2FET** [comment]
Hi, which firmware version are you using? The latest one (1.1.6)?

**Comment by rawzen** [comment]
Yes. It is version 1.1.6.

mån 21 mars 2022 kl. 08:37 skrev Bartosz Cichocki ***@***.***

**Comment by SP2FET** [comment]
Hi, this one should be fixed in the coming release, so I'll close the issue. Thank you for reporting!
