### ISSUE TITLE
Music erroneously added to firmware images(?)

### ISSUE THREAD

**Issue by GravisZro** [mudita/MuditaOS#3727]
# 🐛 Bug report

## 📝 Description

I'm not sure if it's part of the firmware currently being distributed but after mounting my Pure Phone as an USB MTP device using FUSE, there were nine MP3s by artist _Nick Lewis_ already loaded.  I presume these files were added during testing and someone forgot to remove them before deployment.

## 🔬 Minimal reproduction
Mount the Pure Phone as a USB MTP device.

## 🌍 Your operating system and MuditaOS version

1.2.0

**Comment by mjan-dev** [comment]
Those files has been included on purpose - we wanted to share some good music with you and this has been approved by the artist.
