### ISSUE TITLE
Apostrophe

### ISSUE THREAD

**Issue by LizGalanis** [mudita/MuditaOS#3728]
# ⚠️ Create other issue

## 📝 Description
When texting there is no apostrophe available when pressing 1 to get punctuation (at least not that I can find!)

## 📝 Describe the solution you'd like
Would love to have access to apostrophes when texting

**Comment by mjan-dev** [comment]
You can find apostrophe sign with *(asterisk) long press. There are more special signs there, not available otherwise.

**Comment by Storms-Engineering** [comment]
Super helpful though and just what I have been looking for!  Might want to place a little more emphasis on that in the user manual.  I don't remember it, but looking in the special keybaord functions long press it is indeed there.
