### ISSUE TITLE
MMS are received but displayed as gibberish data

### ISSUE THREAD

**Issue by esope** [mudita/MuditaOS#3731]
# 🐛 Bug report: MMS are received but displayed as gibberish data

## 📝 Description

When you receive an MMS, the sender is always set as ``8<`` (whatever is the actual sender) and the contents of the MMS is displayed as a list of squares.

## 👍 Expected behavior

At the very least: correctly display the sender of the MMS, and correctly show the text part of the MMS.

## 👎 Current behavior

The sender of an MMS is always ``8<`` (so all MMSes are put in the same discussion, i.e. the one for the contact ``8<``).
The text data of the MMS is unreadable: a list of squares is displayed.

## 🔬 Minimal reproduction

Receive an MMS from a French carrier to a French carrier. (This is not tested outside France)

## 🔍 Provide logs

No logs.

## 🌍 Your operating system and MuditaOS version

MuditaOS 1.2.0

## 🤔 Anything else relevant?

None.

**Comment by mjan-dev** [comment]
MMS messages are currently not supported. We will consider adding more implicit message about MMS not being supported in future versions.
