### ISSUE TITLE
UI bug: Bluetooth window first rendered with off state

### ISSUE THREAD

**Issue by GravisZro** [mudita/MuditaOS#3738]
# 🐛 Bug report

## 📝 Description

When going through the `Menu`->`Settings` menu, when you go to ~~a~~ _the Bluetooth settings_ "window" (as referred to in the code) that has an option enabled (e.g. Bluetooth in the 'ON' state) when first entering the the "window" it will render as the default state (e.g. 'OFF') before immediately being updated to it's actual state.

## 👍 Expected behavior

When entering ~~new windows~~ _the Bluetooth settings window_ through the menu, only the current state should be rendered.

## 👎 Current behavior

When entering ~~new windows~~ _the Bluetooth settings_ through the menu, the default state is rendered and then updated to the current state.

## 🔬 Minimal reproduction

* Go to Menu->Settings->Bluetooth
* Turn on "Bluetooth"
* Go back to Go to Menu->Settings
* Open Go to Menu->Settings->Bluetooth
* The "Bluetooth" open will be rendered as "OFF" and then be updated to "ON"

## 🌍 Your operating system and MuditaOS version
1.2.0

## 🤔 Anything else relevant?
~~This happens with other menu options like "Dark Mode" therefore it's likely an issue in apps-common.~~

**Comment by SP2FET** [comment]
Hi,
The issue is visible in Bluetooth probably due to BT state handling, did you notice this behavior somewhere else too (excluding dark mode, as you mentioned)?

**Comment by GravisZro** [comment]
Yes, I double checked the it's **only** the Bluetooth menu that updates it's switch state.  On closer look examination, the dark mode switch doesn't have this issue.  I checked other switches and they do not have this issue.

**Comment by SP2FET** [comment]
Great, thanks for checking this out. We'll take a look at this. Reported as MOS-421.
