### ISSUE TITLE
Music Application: global music mode

### ISSUE THREAD

**Issue by GravisZro** [mudita/MuditaOS#3739]
# 🚀 Feature request

## 📝 Description

Currently, you can only listen to music if you are in `Menu`->`Music` and going to do anything else (e.g. browse messages, edit contacts, etc.) halts music playback.

## 📝 Describe the solution you'd like

In the music player, the left green key should be labeled "Foreground"/"Background" depending on if the music playback service keeps running while using other applications.

## 📝 Describe alternatives you've considered

The music player could remember where playback stopped but that wouldn't be as good... but it should do that anyway.

**Comment by mjan-dev** [comment]
This is already on our roadmap for coming months. The music player functionality is really lacking and there is a lot space for improvement. 
The issue described will be fixed as first one.
