### ISSUE TITLE
Alarm application - UI bug: time entry not zero padded

### ISSUE THREAD

**Issue by GravisZro** [mudita/MuditaOS#3747]
# 🐛 Bug report

## 📝 Description

When entering an alarm time, the number of minutes will remain a single digit if only one digit is entered, resulting in 7:1 AM being a valid time.

## 👍 Expected behavior

Upon leaving each the numeric entry field for hour and minutes, zero padding should be applied.  This may be relevant for hours field as well depending on if 24 hour mode is selected.

## 👎 Current behavior

After entering a single digit in the minutes field, the field will remain a single digit after the field is left.

## 🔬 Minimal reproduction

* Create new alarm
* Clear the minutes field
* Enter '1' in the minutes field
* Leave the minutest field

**Comment by SP2FET** [comment]
Hi, 
Indeed, it's a bug. Reported as MOS-418
