### ISSUE TITLE
Music application - UI improvement: switch to playback interface when song is played

### ISSUE THREAD

**Issue by GravisZro** [mudita/MuditaOS#3750]
# 🚀 Feature request

## 📝 Description

Currently when you select a song to play, you have to press "Back" and then press the up direction to get to the music playback UI.

## 📝 Describe the solution you'd like

When you select a song to begin playing then it should "bring down" the music playback UI.  While playing music in the music playback UI, pressing down should jump to the current song being played in the song menu list.

**Comment by Lefucjusz** [comment]
Hi @GravisZro, due to the business decision we've decided to not implement this functionality. I'm closing this ticket now.
