### ISSUE TITLE
Workflow: Unable to pass "PR Tasks Completed Check"

### ISSUE THREAD

**Issue by GravisZro** [mudita/MuditaOS#3751]
# 🐛 Workflow bug report

## 📝 Description

I appended the required text in the PR #3720 (and others) but the check keeps failing with
> **Error:** Resource not accessible by integration

## 🔍 Provide logs
Here's the status page for PR #3720: https://github.com/mudita/MuditaOS/runs/6028167829?check_suite_focus=true

**Comment by SP2FET** [comment]
Hi, 
I know about this issue, and will try to fix it in the coming days, but as it affects only community PRs, I'll merge them by hand until it will be fixed.
