### ISSUE TITLE
Delete All Calls in Call Log

### ISSUE THREAD

**Issue by Storms-Engineering** [mudita/MuditaOS#3755]
# 🚀 Feature request
Delete All Calls in Call Log
## 📝 Description
Be able to delete All Calls in Call Log

## 📝 Describe the solution you'd like
You can use the existing options menu, but simply add a "delete all calls" option

## 📝 Describe alternatives you've considered
Deleting every call by hand is kind of annoying.  And i was just thinking that over a couple years the amount of calls might be a lot, and it might slow the phone down.

**Comment by pholat** [comment]
Thanks for your feedback! The requested feature was added internally for planning ( Internal link for our reference https://appnroll.atlassian.net/browse/MOS-447 )

**Comment by mjan-dev** [comment]
@Storms-Engineering FYI this feature is in progress right now :+1:

**Comment by Storms-Engineering** [comment]
@mjan-dev @marziel  Sweet! Thanks guys!

**Comment by marziel** [comment]
@Storms-Engineering You're welcome! :)
