### ISSUE TITLE
Alarm crash

### ISSUE THREAD

**Issue by snan** [mudita/MuditaOS#3779]
Phone crashed when the alarm went of while I was at the alarms list screen.

<small>also had a ton of dropped calls today as per ushe which is off topic to the alarm crash but just a follow up.</small>

**Comment by pholat** [comment]
@snan please send the report on Mudita Center so that we would have a crash dump and would be able to reproduce the issue :bow:

**Comment by snan** [comment]
I tried and I started Mudita Center, it asked me to update it and after I did that, connecting (between phone & computer) worked once but then it disconnected and this is my life now:
![IMG_0929](https://user-images.githubusercontent.com/309417/166256029-87d435dc-d43c-41e0-9d79-aaf312c5e86d.jpeg)

**Comment by mjan-dev** [comment]
Tried to reproduce the alarm issue many times on 1.2.0 but with no success.

**Comment by pholat** [comment]
@snan would you be so kind to tell me if:
- your MC application is up to date?
- this problem with communication is persistent?

**Comment by pholat** [comment]
edit: we found some similar issue internally ( internal reference: https://github.com/mudita/MuditaOS/issues/3779 )

**Comment by snan** [comment]
How do I send logs from MC? Since I've intermittently gotten it to connect again.

**Comment by mjan-dev** [comment]
@snan I'm attaching a forum link with a quick description on how to do it. 
https://forum.mudita.com/t/how-to-send-logs-to-mudita-via-mudita-center/4085

**Comment by Lefucjusz** [comment]
@snan Have you sent the logs to Mudita via the Mudita Center?

**Comment by snan** [comment]
Ah, I didn't see that Urszula had replied in the thread! I'll try again now

**Comment by Lefucjusz** [comment]
@snan Please try to update to the latest release - 1.4.0. We've fixed a lot of bugs regarding stability issues since your report, so the OS should be now much stable.
