### ISSUE TITLE
Messages UI: Add conversation dividers

### ISSUE THREAD

**Issue by GravisZro** [mudita/MuditaOS#3796]
# 🚀 Feature request

## 📝 Description

The text message conversation log should have a divider between the days.  This would solve issue #3428.

## 📝 Describe the solution you'd like

The divider should include the date for the messages above with an upward arrow as well as the date for the messages below with a downward arrow.

## 📝 Describe alternatives you've considered

Putting the full datetime stamp on a message would work but it wouldn't be as good if it only shows when highlighted.

**Comment by pholat** [comment]
@GravisZro please do fill in the proposal in the bug referenced as it's a proposal to fix the issue mentioned there. It will help us to not duplicate issues.
