### ISSUE TITLE
Messages and calls not coming through

### ISSUE THREAD

**Issue by LizGalanis** [mudita/MuditaOS#3816]
# 🐛 Bug report

## 📝 Description

Since the latest update suspected that I wasn't receiving some texts. I have tried messaging and calling myself from my partner's phone, and calls and texts only come through about half of the time, even when I have reception. My messages also often do not send, despite having cell reception and I have to re-send. 

## 👍 Expected behavior

Reliably receiving texts and calls

## 👎 Current behavior

The ability to receive texts and calls is intermittent

## 🔬 Minimal reproduction

I'm not sure what causes the texts and calls to not come through. Moving location doesn't change the issue. Cell reception doesn't change the issue. If I simply send myself 3 texts and call myself a few times from another phone, I certainly will not receive all these calls and texts. 

Issues that don't have enough info and can't be reproduced will be closed.

## 🔍 Provide logs

Please paste relevant logs below or attach them to this issue.

<pre><code>

</code></pre>

## 🤔 Anything else relevant?

**Comment by mjan-dev** [comment]
Hi @LizGalanis. Thanks for reporting. We have some idea of what could cause this problem and are working on a possible fix. Would it be possible to send a report through Mudita Center so we can make sure this is the same issue?

**Comment by LizGalanis** [comment]
Hi Mjan, can you let me know the steps for sending a report through Mudita Centre?

**Comment by pholat** [comment]
You can check the relevant how-to on our forum here: https://forum.mudita.com/t/how-to-send-logs-to-mudita-via-mudita-center/4085

**Comment by Lefucjusz** [comment]
@[LizGalanis](https://github.com/LizGalanis) Have you sent the logs to Mudita via Mudita Center?

**Comment by LizGalanis** [comment]
Hi Lefucjusz, I have sent one now. It's a while since I've used the phone though so I'm not sure if it's helpful? I had to stop using the phone since I could not rely on it for calls, texts or alarm clock.

**Comment by Lefucjusz** [comment]
@LizGalanis The issue has been reported under MOS-395 ticket.

**Comment by Lefucjusz** [comment]
Hi @LizGalanis, sorry for the late update - the issue has been fixed in 1.4.0 MuditaOS version. Closing this thread now.
