### ISSUE TITLE
AptX support.

### ISSUE THREAD

**Issue by githubtefo** [mudita/MuditaOS#3838]
# 🚀 Feature request

## 📝 Description

Add HiFi support for bluetooth devices.

## 📝 Describe the solution you'd like

As it's been done in other open source projects for Android devices
https://github.com/EHfive/pulseaudio-modules-bt 

## 📝 Describe alternatives you've considered

Have you considered any alternative solutions or workarounds?

**Comment by SP2FET** [comment]
Hi, we're not planning to use the AptX codec right now as the implementation is not so trivial. We'll be using AAC codec though, so it will provide you with a better quality than SBC, which is used right now
