### ISSUE TITLE
Caldav support.

### ISSUE THREAD

**Issue by githubtefo** [mudita/MuditaOS#3839]
# 🚀 Feature request

## 📝 Description

Add Caldav synchronizer features to support open source calendar, like Nextcloud.

## 📝 Describe the solution you'd like

If you have a solution in mind, please describe it.

## 📝 Describe alternatives you've considered

Have you considered any alternative solutions or workarounds?

**Comment by SP2FET** [comment]
As for now, we have basic calendar functionality, which will be extended and rewritten to be able to sync and use with our companion app - Mudita Center. If you wish to have CalDav support, we encourage you to take a challenge and try to write it by yourself!
