### ISSUE TITLE
Mudita sometimes stucked on "Turn off the phone?"

### ISSUE THREAD

**Issue by gabryatfendor** [mudita/MuditaOS#3840]
# 🐛 Bug report

## 📝 Description

When checking the phone it's stucked at the screen "Turn off the phone?" (I don't know if I accidentally pressed the turn off key while in my pocket) and I can't do anything until the auto-lock activates and, from there on, everything works normally. During the freeze the only button that works is the switch between mode.

## 👍 Expected behavior

Mudita OS should not be freezed

## 👎 Current behavior
Mudita OS is freezed until the auto-lock activates

## 🔬 Minimal reproduction

I don't have really a step-by-step to reproduce, since I noticed this behavior twice in a couple of days when checking my phone

## 🌍 Your operating system and MuditaOS version

Mudita OS 1.2.0

## 🤔 Anything else relevant?

**Comment by mjan-dev** [comment]
Hi @gabryatfendor! Thanks for reporting. Would it be possible to send a report through Mudita Center? We would be able to look at logs from your device as we haven't observed such behavior yet.

**Comment by gabryatfendor** [comment]
I have enabled the automatic send of the logs from the Mudita Center already. Do I have to send them manually in any other way?

**Comment by SP2FET** [comment]
Hi, Sorry for the late response.
The issue indeed exists. we are able to somehow reproduce it. It's already reported under the MOS-210 ticket.

**Comment by SP2FET** [comment]
Hi, FYI it's still in progress

**Comment by Lefucjusz** [comment]
The issue has been solved and will be fixed in the next MuditaOS release.
