### ISSUE TITLE
Contacts: Add hidden entries/known numbers

### ISSUE THREAD

**Issue by GravisZro** [mudita/MuditaOS#3928]
# 🚀 Feature request

## 📝 Description

I have a bunch of contacts that are bots which that send text messages to me on occasion (e.g. ISP company, Credit Card company, Dentist, Doctor, Pharmacy, School, etc.).  I want to be able to know which bot is sending a message so I add them to my `Contacts`.  However, I _never_ want to call them so being visible (by default) in `Contacts` is undesirable.

## 📝 Describe the solution you'd like

When adding a contact, a new checkbox that would enable you to keep an entry hidden would work.  Having an option to "show all" in `Contacts` or simply having them show up in the search function (only if the search is improved though) would make it possible to remove them.

## 📝 Describe alternatives you've considered

An entirely new list of "Known Numbers" which simply let you map a name to a number would also work.

**Comment by SP2FET** [comment]
Hi, it sounds like a nice idea. However, we don't plan to introduce it to the code right now. You can challenge yourself and try to implement this on your own if you would like.
