### ISSUE TITLE
Mudita signal drop with all operators in Egypt

### ISSUE THREAD

**Issue by dr3mro** [mudita/MuditaOS#3981]
📝 Using Mudita Pure with 4 operators here in Egypt all same issue .. signal drops often for hours and I am unreachable for most of day and battery life holds charge only for 1 day max

👍 I expect to have option to set max network mode either LTE/4g/3g/2g as in Egypt we have 4g for internet and when we dial it switches to 3g or 2g for calls and that takes time in Pure to find the network and often fails

🌍  MuditaOS version 1.2.1

**Comment by Lefucjusz** [comment]
@dr3mro Please report an issue through Mudita Center as described in the following link: https://forum.mudita.com/t/how-to-send-logs-to-mudita-via-mudita-center/4085. Additionally please attach the link to this issue, so it will be easier for us to identify your report.
