### ISSUE TITLE
Pure signal indicators show that it has signal but you can't make calls 

### ISSUE THREAD

**Issue by p-sims** [mudita/MuditaOS#3983]
# 🐛 Bug report

## 📝 Description

Phone shows signal bars, but even after a few minutes if you try and make a call it says no network connection. Restarting seems to fix.

## 👍 Expected behavior

Either phone has network connection (and you can make calls) or it doesn't (so should show this in signal indicator)

## 👎 Current behavior

![IMG_1344](https://user-images.githubusercontent.com/64636731/180728092-44391614-0712-44c2-8d1b-2ddba7cf35e3.JPG)

## 🔬 Minimal reproduction

Only had the phone a few days. If I manage to find a way or reproducing this I will post below. 

## 🔍 Provide logs

I will try and report these via MuditaCentre.

## 🌍 Your operating system and MuditaOS version
MuditaOS 1.2.0

**Comment by Lefucjusz** [comment]
@p-sims The fix for this issue is present in 1.3.0, which will be released in a few days. If the problem still persists after the release of the new version, please reopen the issue.
