### ISSUE TITLE
Music Player .m4a file support

### ISSUE THREAD

**Issue by p-sims** [mudita/MuditaOS#3994]
# 🚀 Feature request

## 📝 Description
Currently Music Player doesn't seem to support .m4a files.

## 📝 Describe the solution you'd like
Could it support .m4a files which I understand to be based on more modern compression standard (MPEG4 vs MPEG2)

## 📝 Describe alternatives you've considered
So people could convert all of there .m4a music files to .mp3 which would give slightly lower quality for the same file size. However it would be much more convenient if MuditaOS just supported .m4a rather than everyone have to transcode lots of there music.

There appears to be library for playing back .m4a on embedded devices:
https://github.com/FrankBoesing/Arduino-Teensy-Codec-lib/blob/master/examples/Complete_MP3_AAC_MP4_M4A_example/Complete_MP3_AAC_MP4_M4A_example.ino

**Comment by Lefucjusz** [comment]
@p-sims Thank you for reporting the issue. Redesign of the music player app and adding additional formats support is already on our roadmap, so it'll be added in one of the future releases.
