### ISSUE TITLE
Sim card

### ISSUE THREAD

**Issue by snan** [mudita/MuditaOS#3996]
I think a lot of the issues— can't call, can't text, drops calls, drops texts, hangs up mid call, missed calls—are because it sometimes believes that there's no sim card in there 🤷🏻‍♀️

**Comment by snan** [comment]
Usually restarting it is what makes it understand that it's there

**Comment by Lefucjusz** [comment]
@snan Thanks for reporting the problem, we're sorry for your inconvenience. Please send us logs via Mudita Center, so we can investigate this issue further. 
Quick description how to do this can be found here: https://forum.mudita.com/t/how-to-send-logs-to-mudita-via-mudita-center/4085

**Comment by Lefucjusz** [comment]
@snan Please also provide the serial number of your phone here after you've sent the logs.

**Comment by Lefucjusz** [comment]
Hi @snan, could you provide us with the logs and detailed description of the issue you've been experiencing?

**Comment by Lefucjusz** [comment]
Closing the issue due to lack of response.
