### ISSUE TITLE
Minor localisation issue of German translation

### ISSUE THREAD

**Issue by philebos** [mudita/MuditaOS#4022]
# 🐛 Bug report

## 📝 Description

You want to play a song that is in your music library. You select it and then you would press a "play" button or the appropriate function key. In the display the current function that is assigned to the main round button is displayed. Having set the language to German, "Spiel" is displayed on the screen. 

This is bad German. It is the imperative of the word "play". You would never ever use this form in this context.

## 👍 Expected behavior
Simply change the wording and use "Abspielen".

## 👎 Current behavior

See above...

## 🔬 Minimal reproduction
See above...

## 🔍 Provide logs
No log available. 

<pre><code>

</code></pre>

## 🌍 Your operating system and MuditaOS version

1.3.0

## 🤔 Anything else relevant?

**Comment by Lefucjusz** [comment]
Hi @philebos, thanks for reporting the issue! It is being processed under MOS-664 ticket and will be corrected in next MuditaOS release.
