### ISSUE TITLE
screeen refresh

### ISSUE THREAD

**Issue by dr3mro** [mudita/MuditaOS#4058]
Hi, 
eInk screens use energy when updating only 
Mudita pure in standby mode update screen every minute even if it is not necessary like when using Quotes wallpaper instead of clock 
so either make it not update in standby if Quotes wallpaper is selected or display a small clock in status bar to make that battery drain at least useful no just a pure waste of battery life.

**Comment by dawidwojtas-mudita** [comment]
Hello @dr3mro.
It has been done in 1.3.0 version. If you selected quotes or logo as wallpaper then the system doesn't refresh the screen every minute unless MuditaOS need to change the battery or network status.
