### ISSUE TITLE
create github sponsor option for MuditaOS

### ISSUE THREAD

**Issue by ghost** [mudita/MuditaOS#4109]
I'd love to sponsor this project as I find it inspiring and important given the current cellular ecosystem.

An option to sponsor the project via github sponsors would be great.

**Comment by Lefucjusz** [comment]
Hi! 

As I promised, I'm coming back with the info on this matter. At this moment we're unable to launch GitHub Sponsors option, but we're incredibly grateful for your commitment!

Best regards on behalf of the entire Mudita Team.
