### ISSUE TITLE
Mudita Center Lagging/Freezing

### ISSUE THREAD

**Issue by LizGalanis** [mudita/MuditaOS#4111]
# 🐛 Bug report

## 🔬 Minimal reproduction

Typing texts on Mudita Center

## 🔍 Provide logs

Please paste relevant logs below or attach them to this issue.

<pre><code>

</code></pre>

I sent logs through the issue reporting on Mudita Center

## 🌍 Your operating system and MuditaOS version

macOS Monterey 12.6 Apple M1
Mudita OS 1.4.0
Mudita Center 1.5.3

## 🤔 Anything else relevant?

**Comment by Lefucjusz** [comment]
@LizGalanis please report Mudita Center related issues on the Mudita Center repo: https://github.com/mudita/mudita-center.
