### ISSUE TITLE
Wrong Unread Messages Count Under Some Circumstances

### ISSUE THREAD

**Issue by sarahspock** [mudita/MuditaOS#4198]
# 🐛 Bug report
Mudita OS shows read messages as unread depending on which screen was open before the phone went to sleep. This probably occurs also if the phone hasn't gone to sleep and the phone number of person x is open in messages and you receive a message from person x.

## 👍 Expected behavior

I  did not check the source code but I suspect the OS changes the boolean messageRead from false to true when you click on the phone number in the messages app. You should change this so that the OS also changes the boolean messageRead from false to true when the chat is already open or have the messageRead check be a function where we check the current boolean and check to see if the user currently has the message screen open to the phone number 

## 👎 Current behavior

You only change the messageRead boolean when the user clicks on the messages for phone number x in the messages app (probably)

## 🔬 Minimal reproduction
To reproduce:
1. Open the messages application and go to a chat log for a phone number x
2. Let the phone go to sleep 
3. The phone receives a text from phone number x
4. Open the application and the screen is already open showing the chat log for phone number x, thus the message is read (this happens when corresponding with someone actively, a common use case)
5. Let the phone go to sleep. 
6. Observe that the phone still shows the received message as unread

<pre><code>

</code></pre>

## 🌍 Your operating system and MuditaOS version
1.4

## 🤔 Anything else relevant?

**Comment by Lefucjusz** [comment]
Hi @sarahspock! The bug has been recently resolved and the fix will be present in one of the next MuditaOS releases.
