### ISSUE TITLE
[Harmony] Relaxation end volume fade out

### ISSUE THREAD

**Issue by demoive** [mudita/MuditaOS#4856]
# 🚀 Feature request

## 📝 Description

At the end of a _Relaxation_, the audio ends abruptly – from UX point of view, it's quite harsh and can disturb a positive period of relaxation.

## 📝 Describe the solution you'd like

When ending a _Relaxation_, fadeout the volume.

**Comment by Lefucjusz** [comment]
Hi @demoive, such feature has just been implemented and will be released in one of our next releases.

**Comment by Lefucjusz** [comment]
Hi @demoive, Harmony 2.9.0 containing this feature has just been released, please update your Harmony to the latest version via Mudita Center.
