### ISSUE TITLE
[Harmony] Favourite Relaxation sounds

### ISSUE THREAD

**Issue by demoive** [mudita/MuditaOS#4859]
# 🚀 Feature request

## 📝 Description

During a _Relaxation_ session, I only use a small subset of the available sounds, that is: the ones that I prefer.

## 📝 Describe the solution you'd like

Ability to star/favourite a sound in the _Relaxation_ activity.

## 📝 Describe alternatives you've considered

1. Add an additional "History" category at the top of the list which shows the last N used sounds (by date in descending order).
2. Just sort each category by "previously used on" date

**Comment by Lefucjusz** [comment]
Hi @demoive, thanks for your suggestion! Currently the focus of the team is on different functionalities and system areas, so we're not planning to implement such feature in the near future.
