### ISSUE TITLE
Add EInk Web Browser for Mudita Kompakt

### ISSUE THREAD

**Issue by PHHENS** [mudita/MuditaOS#4896]
# 🚀 Feature request

## 📝 Description

Web browser is a must have app on a phone

## 📝 Describe the solution you'd like

Port and Add EikBro app to mudita kompakt OS
https://github.com/plateaukao/einkbro

**Comment by Lefucjusz** [comment]
@PHHENS This repo contains codebase for MuditaOS, used in Pure and Harmony products, not in Kompakt. Your suggestion was passed to Kompakt team.

I'm closing this request as it's unrelated to MuditaOS.
